### ISSUE TITLE
Web login

### ISSUE THREAD

**Issue by Tandokude** [jdoss/ppngx#1]
First off, great script and I'm not sure if this is an issue or not. But I don't see where in your script you are configuring the web "superuser" so you can log into the site.

**Comment by jdoss** [comment]
Thanks! It's been a while since I have launched a fresh install from this script. IIRC it prompted me to create a new user when it migrates database on PostgreSQL. Did it not do this?

**Comment by Tandokude** [comment]
At least in my case it did not do this, I only mention it cause I know in the official docs it notes:
To be able to login, you will need a super user. To create it, execute the following command:

$ docker-compose run --rm webserver createsuperuser
This will prompt you to set a username, an optional e-mail address and finally a password (at least 8 characters).

I had to use the --tty option to be able to execute this command and get the user created.

**Comment by jdoss** [comment]
I think my additions to the README should clear things up here. If not, we can reopen this issue and work together on making things more clear.

Thanks for taking the time to open this up so I could fix it. :)
