### ISSUE TITLE
login uname & pword?

### ISSUE THREAD

**Issue by xpseudonym** [jdoss/ppngx#10]
First thing first - thank you for this little script  which has made my life much more straight forward than it might have been!

But, I realise this is not a complicated question and I'm sure I should be able to answer it:-
What is the default username and password for Paperless?
![image](https://github.com/jdoss/ppngx/assets/5032475/3abfd2a2-c4e0-41fb-8612-b8fd9fd2e3ad)
I'm having no difficulty with the interface for SFTPGo and the credentials I entered in `start.sh` - on both ports `2022` and `8022` or accessing the Paperless server, but what's the login?  Should I have added the [PAPERLESS_ADMIN_USER](https://docs.paperless-ngx.com/configuration/#PAPERLESS_ADMIN_USER) and [PAPERLESS_ADMIN_PASSWORD](https://docs.paperless-ngx.com/configuration/#PAPERLESS_ADMIN_PASSWORD) to `start.sh`?

**Comment by jdoss** [comment]
You are welcome! I am glad it was helpful. :)

See step 6 in the README.md

![image](https://github.com/jdoss/ppngx/assets/8195/dfcff5f5-dd8e-4055-b852-cb35869dac07)

**Comment by xpseudonym** [comment]
Hmm, uh, bother... Missed that.  I figured it had to be straight forward.  Actually, I think I got to 5, found it worked and went off and partied!  Oops.  Thanks!
That `podman exec` command looks like it can be run before or after setting up the `systemd` units - would that be correct?

**Comment by xpseudonym** [comment]
Hmm, uh, bother... Missed that.  I figured it had to be straight forward.  Actually, I think I got to 5, found it worked and went off and partied!  Oops.  Thanks!
That `podman exec` command looks like it can be run before or after setting up the `systemd` units - would that be correct?
