### ISSUE TITLE
getting deadlock after running backup script

### ISSUE THREAD

**Issue by TonyBostonTB** [jdoss/ppngx#19]
I just installed this today, imported my data from another instance of paperless-ngx, ran the backup script, rebooted and now I can not start the pod via ./start.sh
The error I see is 
```
./start.sh                                                                                                                                                            
Creating Paperless Pod...
24ebb75e35b128422fded0505e5a5c15d6d2f515523fcb6497ae93931af2cee6
Starting Redis...
00e6e23c41f969e709162226282fed247b2a1c1fd59a912ee3579a3cc6fcdea0
Error: please run 'podman system renumber' to resolve deadlocks: container 00e6e23c41f969e709162226282fed247b2a1c1fd59a912ee3579a3cc6fcdea0 and volume paperless-redis share lock ID 2: deadlock due to lock mismatch
```

The 'podman system renumber' did not help

**Comment by jdoss** [comment]
Sorry for the delay in response. Hmmm that is pretty odd. What does `podman ps -a` show for what containers are running when it is in this deadlocked state?

**Comment by TonyBostonTB** [comment]
Can't say. Used another server based on NixOS, imported the regular backup and never looked back.
