### ISSUE TITLE
Do you have a particular back up plan?

### ISSUE THREAD

**Issue by MatthewBregg** [jdoss/ppngx#8]
Hi!

Thanks for this script, it's been working pretty well!

I was wondering what you did to back up. 

I was thinking of either running the document exporter, or backing up each podman volume + the version. 

I was wondering what you did, and if you had a script for it?

Thanks!

**Comment by jdoss** [comment]
Hey there! I am glad it has been useful. :)

I use BTRFS snapshots on my /home BTRFS subvolume and I also use these systemd units  https://github.com/quickvm/restic-systemd-units I made to automate Restic to backup to a secondary volume on my workstation, and to blockstorage via Mino on my NAS.

@runningferret might have something he uses as I think he setup something to use the document exporter but I don't recall the specifics or if he only did an export once. 

That said, If you figure out a good way to export things via script or backing up the podman volumes via systemd timer, PR the steps to the README and we can get it merged as an example on how to back things up correctly.

**Comment by MatthewBregg** [comment]
Thanks, done!

**Comment by jdoss** [comment]
Thanks for the PR. Merged! :)
